name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: get code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: install independency
        run: npm install

      - name: run tests
        run: npm test -- --ci=false

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: get code
        uses: actions/checkout@v3

      - name: build and run server
        run: |
          npm install
          npm start &
          sleep 5
          curl -I http://localhost:3000
