name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci # Faster & more reliable

      - name: Verify Jest is installed
        run: npx jest --version # Debugging step

      - name: Fix Jest permissions (if needed)
        run: chmod +x node_modules/.bin/jest

      - name: Run tests
        run: npx --no-install jest --ci=false # Ensures correct Jest execution

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Get code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Start server
        run: npm start &

      - name: Wait for server to start
        run: sleep 5

      - name: Test if server is running
        run: curl -I http://localhost:3000
