name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Hämta kod
        uses: actions/checkout@v3

      - name: Installera Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Installera beroenden
        run: npm install

      - name: Köra tester
        run: npm test

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Hämta kod
        uses: actions/checkout@v3

      - name: Bygga och köra servern
        run: |
          npm install
          npm start &
          sleep 5
          curl -I http://localhost:3000
